
# Generated by Django 2.1.7 on 2019-03-04 18:31


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('descuentoPorcentual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cambio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero', models.IntegerField(default=0)),
                ('efectivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuentoTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('horaVenta', models.TimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta'),
        ),
    ]
