# Generated by Django 2.1.5 on 2019-02-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Descuento')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cambio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField()),
                ('numero', models.IntegerField(default=0)),
                ('efectivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuentoTotal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Descuento')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta'),
        ),
    ]
